# Generated by Django 4.2 on 2023-04-10 21:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamePortale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='Info',
            field=models.ForeignKey(1, on_delete=django.db.models.deletion.CASCADE, to='gamePortale.info'),
            preserve_default=False,
        ),
    ]
