# Generated by Django 4.2 on 2023-04-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamePortale', '0002_useritem_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='Id',
        ),
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
