# Generated by Django 4.2 on 2023-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamePortale', '0002_credentialsd'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoTpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=10000)),
            ],
        ),
    ]
